api:
  version: 1

logging:
  config: classpath:logback.xml
  level:
    io:
      jaegertracing: DEBUG

# lets listen on all ports to ensure we can be invoked from the pod ip address
# contextPath: /api/v${api.version}/*
server:
  address: 0.0.0.0
  port: 8070

# =============================================
# spring configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:sample-api}
  jpa:
    # log generated sql
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: create-drop
  h2:
    # http://localhost:8080/h2-console
    # connection url: jdbc:h2:mem:testdb
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    # JACKSON (JacksonProperties)
    # Date format string or a fully-qualified date format class name
    #spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OPENSHIFT_SECURITY_ISSUER_URI:http://localhost:8080/auth/realms/sample}
        registration:
          keycloak:
            client-id: ${OPENSHIFT_SECURITY_CLIENT_ID:sample-api}
            client-secret: ${OPENSHIFT_SECURITY_CLIENT_SECRET:19283667-7fb3-41b4-8394-75599045c100}
      resourceserver:
        jwt:
          issuer-uri: ${rest.security.issuer-uri}
          jwk-set-uri: ${OPENSHIFT_SECURITY_JWK_URI:http://localhost:8080/auth/realms/sample/protocol/openid-connect/certs}

# =============================================
# spring security configurations
# ---------------------------------------------
rest:
  security:
    enabled: true
    api-matcher: /api/v1/**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600
    issuer-uri: ${OPENSHIFT_SECURITY_ISSUER_URI:http://localhost:8080/auth/realms/sample}

# =============================================
# spring actuator configurations
# ---------------------------------------------
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      # if you want to change the default prometheus endpoint, just change the 'id' to another value.
      id: prometheus
  endpoints:
    web:
      exposure:
        include: ["*"]
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================
# opentracing configurations
# ---------------------------------------------
opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector:14268/api/traces

jaeger.tracer:
  host: ${OPENSHIFT_JAEGER_HOST:jaeger-agent.CHANGEME.svc}
  port: 6831
