api:
  version: 1

logging:
  config: classpath:logback.xml

# lets listen on all ports to ensure we can be invoked from the pod ip address
# contextPath: /api/v${api.version}/*
server:
  address: 0.0.0.0
  port: 8070

# =============================================
# spring configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:product-api}
  jpa:
    # log generated sql
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: create-drop
  h2:
    # http://localhost:8080/h2-console
    # connection url: jdbc:h2:mem:testdb
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    # JACKSON (JacksonProperties)
    # Date format string or a fully-qualified date format class name
    #spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            # required for application bootstrap
            issuer-uri: ${OPENSHIFT_SECURITY_ISSUER_URI:http://localhost:8080/auth/realms/codigofonte}
        registration:
          keycloak:
            client-id: ${OPENSHIFT_SECURITY_CLIENT_ID:product-api}
            client-secret: ${OPENSHIFT_SECURITY_CLIENT_SECRET:f87c6fe9-2155-4c28-bb04-68f8983b5ad1}
      resourceserver:
        jwt:
          issuer-uri: ${OPENSHIFT_SECURITY_ISSUER_URI:http://localhost:8080/auth/realms/codigofonte}
          jwk-set-uri: ${OPENSHIFT_SECURITY_JWK_URI:http://localhost:8080/auth/realms/codigofonte/protocol/openid-connect/certs}

# =============================================
# spring security configurations
# ---------------------------------------------
rest:
  security:
    enabled: true
    api-matcher: /api/v1/**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600
    issuer-uri: ${OPENSHIFT_SECURITY_ISSUER_URI:http://localhost:8080/auth/realms/codigofonte}

# =============================================
# spring doc configurations
# ---------------------------------------------

springdoc:
  packagesToScan:
    - com.redhat.keycloak.controller
  pathsToMatch:
    - /v1
    - /api/v1/**
    - /v1/**
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: true
